export const nutKeymap: Record<string, string> = {
    "Q": "Q",
    "W": "W",
    "E": "E",
    "R": "R",
    "T": "T",
    "Y": "Y",
    "U": "U",
    "I": "I",
    "O": "O",
    "P": "P",
    "A": "A",
    "S": "S",
    "D": "D",
    "F": "F",
    "G": "G",
    "H": "H",
    "J": "J",
    "K": "K",
    "L": "L",
    "Z": "Z",
    "X": "X",
    "C": "C",
    "V": "V",
    "B": "B",
    "N": "N",
    "M": "M",
    "1": "Num1",
    "2": "Num2",
    "3": "Num3",
    "4": "Num4",
    "5": "Num5",
    "6": "Num6",
    "7": "Num7",
    "8": "Num8",
    "9": "Num9",
    "0": "Num0",
    "SECTION": "Grave",
    "MINUS": "Minus",
    "EQUALS": "Equal",
    "BACKSLASH": "Backslash",
    "SQUARE BRACKET OPEN": "LeftBracket",
    "SQUARE BRACKET CLOSE": "RightBracket",
    "SEMICOLON": "Semicolon",
    "QUOTE": "Quote",
    "COMMA": "Comma",
    "DOT": "Period",
    "FORWARD SLASH": "Slash",
    "LEFT CTRL": "LeftControl",
    "LEFT ALT": "LeftAlt",
    "LEFT SHIFT": "LeftShift",
    "LEFT META": "LeftMeta",
    "RIGHT CTRL": "RightControl",
    "RIGHT ALT": "RightAlt",
    "RIGHT SHIFT": "RightShift",
    "RIGHT META": "RightMeta",
    "F1": "F1",
    "F2": "F2",
    "F3": "F3",
    "F4": "F4",
    "F5": "F5",
    "F6": "F6",
    "F7": "F7",
    "F8": "F8",
    "F9": "F9",
    "F10": "F10",
    "F11": "F11",
    "F12": "F12",
    "TAB": "Tab",
    "CAPS LOCK": "CapsLock",
    "BACKSPACE": "Backspace",
    "RETURN": "Enter",
    "SPACE": "Space",
    "INS": "Insert",
    "DELETE": "Delete",
    "HOME": "Home",
    "END": "End",
    "PAGE UP": "PageUp",
    "PAGE DOWN": "PageDown",
    "UP ARROW": "Up",
    "DOWN ARROW": "Down",
    "LEFT ARROW": "Left",
    "RIGHT ARROW": "Right",
    "NUM LOCK": "NumLock",
    "NUMPAD 0": "NumPad0",
    "NUMPAD 1": "NumPad1",
    "NUMPAD 2": "NumPad2",
    "NUMPAD 3": "NumPad3",
    "NUMPAD 4": "NumPad4",
    "NUMPAD 5": "NumPad5",
    "NUMPAD 6": "NumPad6",
    "NUMPAD 7": "NumPad7",
    "NUMPAD 8": "NumPad8",
    "NUMPAD 9": "NumPad9",
    "NUMPAD PLUS": "Add",
    "NUMPAD MINUS": "Subtract",
    "NUMPAD MULTIPLY": "Multiply",
    "NUMPAD DIVIDE": "Divide",
    "NUMPAD RETURN": "NumPadEqual",
    "NUMPAD DOT": "Decimal"
};
