import { Key } from '@nut-tree-fork/nut-js';

export const nutKeymap: Record<string, Key> = {
    'Q': Key.Q,
    'W': Key.W,
    'E': Key.E,
    'R': Key.R,
    'T': Key.T,
    'Y': Key.Y,
    'U': Key.U,
    'I': Key.I,
    'O': Key.O,
    'P': Key.P,
    'A': Key.A,
    'S': Key.S,
    'D': Key.D,
    'F': Key.F,
    'G': Key.G,
    'H': Key.H,
    'J': Key.J,
    'K': Key.K,
    'L': Key.L,
    'Z': Key.Z,
    'X': Key.X,
    'C': Key.C,
    'V': Key.V,
    'B': Key.B,
    'N': Key.N,
    'M': Key.M,
    '1': Key.Num1,
    '2': Key.Num2,
    '3': Key.Num3,
    '4': Key.Num4,
    '5': Key.Num5,
    '6': Key.Num6,
    '7': Key.Num7,
    '8': Key.Num8,
    '9': Key.Num9,
    '0': Key.Num0,
    'SECTION': Key.Grave,
    'MINUS': Key.Minus,
    'EQUALS': Key.Equal,
    'BACKSLASH': Key.Backslash,
    'SQUARE BRACKET OPEN': Key.LeftBracket,
    'SQUARE BRACKET CLOSE': Key.RightBracket,
    'SEMICOLON': Key.Semicolon,
    'QUOTE': Key.Quote,
    'COMMA': Key.Comma,
    'DOT': Key.Period,
    'FORWARD SLASH': Key.Slash,
    'LEFT CTRL': Key.LeftControl,
    'LEFT ALT': Key.LeftAlt,
    'LEFT SHIFT': Key.LeftShift,
    'LEFT META': Key.LeftMeta,
    'RIGHT CTRL': Key.RightControl,
    'RIGHT ALT': Key.RightAlt,
    'RIGHT SHIFT': Key.RightShift,
    'RIGHT META': Key.RightMeta,
    'F1': Key.F1,
    'F2': Key.F2,
    'F3': Key.F3,
    'F4': Key.F4,
    'F5': Key.F5,
    'F6': Key.F6,
    'F7': Key.F7,
    'F8': Key.F8,
    'F9': Key.F9,
    'F10': Key.F10,
    'F11': Key.F11,
    'F12': Key.F12,
    'TAB': Key.Tab,
    'CAPS LOCK': Key.CapsLock,
    'BACKSPACE': Key.Backspace,
    'RETURN': Key.Enter,
    'SPACE': Key.Space,
    'INS': Key.Insert,
    'DELETE': Key.Delete,
    'HOME': Key.Home,
    'END': Key.End,
    'PAGE UP': Key.PageUp,
    'PAGE DOWN': Key.PageDown,
    'UP ARROW': Key.Up,
    'DOWN ARROW': Key.Down,
    'LEFT ARROW': Key.Left,
    'RIGHT ARROW': Key.Right,
    'NUM LOCK': Key.NumLock,
    'NUMPAD 0': Key.NumPad0,
    'NUMPAD 1': Key.NumPad1,
    'NUMPAD 2': Key.NumPad2,
    'NUMPAD 3': Key.NumPad3,
    'NUMPAD 4': Key.NumPad4,
    'NUMPAD 5': Key.NumPad5,
    'NUMPAD 6': Key.NumPad6,
    'NUMPAD 7': Key.NumPad7,
    'NUMPAD 8': Key.NumPad8,
    'NUMPAD 9': Key.NumPad9,
    'NUMPAD PLUS': Key.Add,
    'NUMPAD MINUS': Key.Subtract,
    'NUMPAD MULTIPLY': Key.Multiply,
    'NUMPAD DIVIDE': Key.Divide,
    'NUMPAD RETURN': Key.NumPadEqual,
    'NUMPAD DOT': Key.Decimal,
}